name: Jacoco Test Coverage Check

# Pull Request가 열리거나, 업데이트되거나, 다시 열릴 때마다 실행
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Pull Request에 코멘트를 작성하기 위한 권한 설정
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # 1단계: 코드 체크아웃
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2단계: JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3단계: Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4단계: 테스트 실행 및 커버리지 리포트 생성
      - name: Test with Gradle
        run: |
          ./gradlew clean test jacocoTestReport

      # 5단계: Jacoco 커버리지 리포트 생성 및 PR 코멘트 작성
      - name: Test Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          title: Test Coverage Report
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
        #  min-coverage-overall: 70
        #  min-coverage-changed-files: 70
